export const diario = [
    { diarioHora: "00:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "01:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "02:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "03:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "04:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "05:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "06:00", diarioImagen: "./assets/SVG/sunrise-fill.svg" },
    { diarioHora: "07:00", diarioImagen: "./assets/SVG/sunrise-fill.svg" },
    { diarioHora: "08:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "09:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "10:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "11:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "12:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "13:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "14:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "15:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "16:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "17:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "18:00", diarioImagen: "./assets/SVG/fat_sunny.svg" },
    { diarioHora: "19:00", diarioImagen: "./assets/SVG/sunset.svg" },
    { diarioHora: "20:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "21:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "22:00", diarioImagen: "./assets/SVG/moon.svg" },
    { diarioHora: "23:00", diarioImagen: "./assets/SVG/moon.svg" },
];

